version: "3.8"

services:
  db:
    image: postgres:13
    container_name: FINANCE_CORE_DB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: FINANCE_CORE_REDIS
    ports:
      - "6379:6379"
    restart: always

  celery:
    build: .
    container_name: FINANCE_CORE_CELERY
    command: celery -A FINANCE_CORE.celery worker -l INFO --concurrency=4
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    restart: always

  celerybeat:
    build: .
    container_name: FINANCE_CORE_CELERY_BEAT
    command: celery -A FINANCE_CORE.celery beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FINANCE_CORE_SERVER
    command: sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    driver: local
