# Generated by Django 5.1.4 on 2025-01-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_category_per_user",
        ),
        migrations.RemoveField(
            model_name="category",
            name="user",
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_category"
            ),
        ),
    ]
