# Generated by Django 5.1.4 on 2025-01-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0003_alter_debt_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="email_sent_for_due_soon",
            field=models.BooleanField(default=False),
        ),
    ]
